
name: funrobo_hw
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tk
  - numpy=1.24.2
  - scipy
  - matplotlib
  - ipython
  - pytest
  - pyyaml
  - pygame
  - pynput

  - pip:
      - inputs==0.5
      - lgpio==0.2.2.0
      - pigpio==1.78
      - pyserial==3.5
      - rpi-lgpio==0.6
      - rpi-ws281x==5.0.0
      - smbus2==0.4.2
      - opencv-python==4.11.0.86
      - -e .
